import type { Metadata } from "next";
import dynamic from 'next/dynamic';
import { Inter } from "next/font/google";
import { Suspense } from 'react';
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import StoreProvider from "./StoreProvider";
const Loader = dynamic(() => import("@/components/common/Loader"))

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spiritual Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loader text="Loading.." />}>
          <main className="bg-slate-700 [scrollbar-gutter:stable]">
            <Toaster position="bottom-right" />
            <StoreProvider>
              {children}
            </StoreProvider>
          </main>
        </Suspense>
      </body>
    </html>
  );
}